version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "spap"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zkjxpguoiis"
s3_prefix = "spap"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "SpaRoot=\"spa\""
